/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/signon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signon */
        post: operations["signon_api_session_signon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_session_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/signoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signoff */
        post: operations["signoff_api_session_signoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_api_files__file_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_number}/fields/{field_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field */
        get: operations["get_field_api_files__file_number__fields__field_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_number}/xrefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cross Refs */
        get: operations["list_cross_refs_api_files__file_number__xrefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_number}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_files__file_number__entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_number}/entries/{ien}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_api_files__file_number__entries__ien__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{ien}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package */
        get: operations["get_package_api_packages__ien__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{ien}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Files By Package */
        get: operations["files_by_package_api_packages__ien__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CrossRefInfo
         * @description One cross-reference on a FileMan file.
         */
        CrossRefInfo: {
            /** Ien */
            ien: string;
            /** File Number */
            file_number: number;
            /** Name */
            name: string;
            /**
             * Xref Type
             * @default
             */
            xref_type: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * Entry
         * @description One FileMan entry (row).
         *
         *     ``fields`` is keyed by FileMan field number — callers usually know
         *     the numbers ahead of time (they requested them via the ``fields``
         *     param of DDR GETS or DDR LISTER). When we list entries with a
         *     default field set (just .01), ``fields`` holds just that field.
         */
        Entry: {
            /** File Number */
            file_number: number;
            /** Ien */
            ien: string;
            /** Fields */
            fields?: {
                [key: string]: components["schemas"]["FieldValue"];
            };
        };
        /**
         * EntryPage
         * @description A paginated slice of entries + a cursor for the next page.
         *
         *     ``next_cursor`` is the last ``external_value`` (usually the .01
         *     field) from this page — pass it back as ``cursor`` to fetch the
         *     next page. ``None`` when the page is the last.
         */
        EntryPage: {
            /** File Number */
            file_number: number;
            /** Entries */
            entries: components["schemas"]["Entry"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * FieldDef
         * @description One field in a FileMan file.
         */
        FieldDef: {
            /** File Number */
            file_number: number;
            /** Field Number */
            field_number: number;
            /** Label */
            label: string;
            type: components["schemas"]["TypeSpec"];
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Storage
             * @default
             */
            storage: string;
            /**
             * Input Transform
             * @default
             */
            input_transform: string;
            /**
             * Help Prompt
             * @default
             */
            help_prompt: string;
            /** Description */
            description?: string[];
            /** Set Values */
            set_values?: {
                [key: string]: string;
            };
        };
        /**
         * FieldValue
         * @description One field value on an entry — external (resolved) form by default.
         *
         *     FLAGS="E" on DDR GETS ENTRY DATA returns external form (dates
         *     rendered, pointers resolved, set codes labeled). We never see the
         *     internal form unless the caller explicitly asked for it.
         *     See LESSONS-LEARNED L18.
         */
        FieldValue: {
            /** Field Number */
            field_number: number;
            /** Value */
            value: string;
            /**
             * Is External
             * @default true
             */
            is_external: boolean;
        };
        /**
         * FileDef
         * @description One FileMan file's header + field list.
         */
        FileDef: {
            /** File Number */
            file_number: number;
            /** Label */
            label: string;
            /** Global Root */
            global_root: string;
            /**
             * Package
             * @default
             */
            package: string;
            /** Description */
            description?: string[];
            /** Fields */
            fields?: {
                [key: string]: components["schemas"]["FieldDef"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PackageDef
         * @description One PACKAGE entry from file 9.4.
         *
         *     ``prefix`` is the M namespace (e.g. ``XU``, ``OR``). ``files`` is
         *     populated only when the caller drills into the FILE subfile
         *     (``^DIC(9.4, IEN, 4, ...)``) — in a basic listing it's empty.
         *     LESSONS-LEARNED L12 notes that some sites ship a PACKAGE entry
         *     with a blank prefix; that's a data-quality issue, not a bug.
         */
        PackageDef: {
            /** Ien */
            ien: string;
            /** Name */
            name: string;
            /**
             * Prefix
             * @default
             */
            prefix: string;
            /**
             * Short Description
             * @default
             */
            short_description: string;
            /** Files */
            files?: number[];
        };
        /** SessionInfo */
        SessionInfo: {
            /** Duz */
            duz: string;
            /** User Name */
            user_name: string;
            /** Site Id */
            site_id: string;
            /** Uci */
            uci: string;
            /** App Context */
            app_context: string;
        };
        /** SignonRequest */
        SignonRequest: {
            /** Access */
            access: string;
            /** Verify */
            verify: string;
            /**
             * Site Id
             * @default vehu
             */
            site_id: string;
        };
        /**
         * TypeSpec
         * @description Decomposed FileMan type.
         *
         *     ``raw`` preserves the exact string from ``^DD`` for display and
         *     audit; all other fields are interpretation of it.
         */
        TypeSpec: {
            /** Raw */
            raw: string;
            /** Base */
            base: string;
            /** Name */
            name: string;
            /**
             * Is Required
             * @default false
             */
            is_required: boolean;
            /**
             * Is Audit
             * @default false
             */
            is_audit: boolean;
            /**
             * Is Multiple
             * @default false
             */
            is_multiple: boolean;
            /** Pointer File */
            pointer_file?: number | null;
            /** Numeric Width */
            numeric_width?: number | null;
            /** Numeric Decimals */
            numeric_decimals?: number | null;
            /**
             * Modifiers
             * @default
             */
            modifiers: string;
            /**
             * Lowercase Mods
             * @default
             */
            lowercase_mods: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signon_api_session_signon_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_session_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signoff_api_session_signoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_files_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_files__file_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_number: number;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_api_files__file_number__fields__field_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_number: number;
                field_number: number;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cross_refs_api_files__file_number__xrefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_number: number;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossRefInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_files__file_number__entries_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                file_number: number;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_api_files__file_number__entries__ien__get: {
        parameters: {
            query?: {
                fields?: string;
            };
            header?: never;
            path: {
                file_number: number;
                ien: string;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_packages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageDef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_api_packages__ien__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ien: string;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageDef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    files_by_package_api_packages__ien__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ien: string;
            };
            cookie?: {
                fm_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
